version: '3.8'

services:
  aitool:
    image: aitool-runtime
    container_name: aitool
    ports:
      - "3000:3000"
    volumes:
      - ./.env.local:/app/.env.local:ro
      - ./src:/app/src
      - ./public:/app/public
    working_dir: /app
    command: npm run start